"""Initial schema

Revision ID: 087e53b0fbf1
Revises: 
Create Date: 2025-11-22 17:05:18.187143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '087e53b0fbf1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency_per_day', sa.Integer(), nullable=False),
    sa.Column('preferred_times', sa.ARRAY(sa.Time()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('wake_time', sa.Time(), nullable=True),
    sa.Column('sleep_time', sa.Time(), nullable=True),
    sa.Column('screens_off_time', sa.Time(), nullable=True),
    sa.Column('bed_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('can_interrupt', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_calendar_events_end_time', 'calendar_events', ['end_time'], unique=False)
    op.create_index('idx_calendar_events_start_time', 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.create_table('correlations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('behavior_pattern', sa.Text(), nullable=False),
    sa.Column('outcome_pattern', sa.Text(), nullable=False),
    sa.Column('correlation_strength', sa.Numeric(), nullable=True),
    sa.Column('confidence_level', sa.Numeric(), nullable=True),
    sa.Column('time_lag_hours', sa.Integer(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_correlations_analysis_date', 'correlations', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_correlations_id'), 'correlations', ['id'], unique=False)
    op.create_table('garmin_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_type', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_garmin_data_data_type', 'garmin_data', ['data_type'], unique=False)
    op.create_index('idx_garmin_data_timestamp', 'garmin_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_garmin_data_id'), 'garmin_data', ['id'], unique=False)
    op.create_table('historical_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('time_period', postgresql.TSRANGE(), nullable=True),
    sa.Column('gap_type', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('follow_up_sent', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historical_gaps_category', 'historical_gaps', ['category'], unique=False)
    op.create_index('idx_historical_gaps_priority', 'historical_gaps', ['priority'], unique=False)
    op.create_index(op.f('ix_historical_gaps_id'), 'historical_gaps', ['id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('insight_type', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('actionable', sa.Boolean(), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_generated_at', 'insights', ['generated_at'], unique=False)
    op.create_index('idx_insights_insight_type', 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_id'), 'insights', ['id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('sent_time', sa.DateTime(), nullable=True),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('categories', sa.ARRAY(sa.String(length=100)), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prompts_scheduled_time', 'prompts', ['scheduled_time'], unique=False)
    op.create_index('idx_prompts_status', 'prompts', ['status'], unique=False)
    op.create_index('idx_prompts_user_id', 'prompts', ['user_id'], unique=False)
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('response_structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_responses_category', 'responses', ['category'], unique=False)
    op.create_index('idx_responses_prompt_id', 'responses', ['prompt_id'], unique=False)
    op.create_index('idx_responses_timestamp', 'responses', ['timestamp'], unique=False)
    op.create_index(op.f('ix_responses_id'), 'responses', ['id'], unique=False)
    op.create_table('behaviors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('behavior_type', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behaviors_behavior_type', 'behaviors', ['behavior_type'], unique=False)
    op.create_index('idx_behaviors_category', 'behaviors', ['category'], unique=False)
    op.create_index('idx_behaviors_timestamp', 'behaviors', ['timestamp'], unique=False)
    op.create_index(op.f('ix_behaviors_id'), 'behaviors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behaviors_id'), table_name='behaviors')
    op.drop_index('idx_behaviors_timestamp', table_name='behaviors')
    op.drop_index('idx_behaviors_category', table_name='behaviors')
    op.drop_index('idx_behaviors_behavior_type', table_name='behaviors')
    op.drop_table('behaviors')
    op.drop_index(op.f('ix_responses_id'), table_name='responses')
    op.drop_index('idx_responses_timestamp', table_name='responses')
    op.drop_index('idx_responses_prompt_id', table_name='responses')
    op.drop_index('idx_responses_category', table_name='responses')
    op.drop_table('responses')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_index('idx_prompts_user_id', table_name='prompts')
    op.drop_index('idx_prompts_status', table_name='prompts')
    op.drop_index('idx_prompts_scheduled_time', table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_insights_id'), table_name='insights')
    op.drop_index('idx_insights_insight_type', table_name='insights')
    op.drop_index('idx_insights_generated_at', table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_historical_gaps_id'), table_name='historical_gaps')
    op.drop_index('idx_historical_gaps_priority', table_name='historical_gaps')
    op.drop_index('idx_historical_gaps_category', table_name='historical_gaps')
    op.drop_table('historical_gaps')
    op.drop_index(op.f('ix_garmin_data_id'), table_name='garmin_data')
    op.drop_index('idx_garmin_data_timestamp', table_name='garmin_data')
    op.drop_index('idx_garmin_data_data_type', table_name='garmin_data')
    op.drop_table('garmin_data')
    op.drop_index(op.f('ix_correlations_id'), table_name='correlations')
    op.drop_index('idx_correlations_analysis_date', table_name='correlations')
    op.drop_table('correlations')
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.drop_index('idx_calendar_events_start_time', table_name='calendar_events')
    op.drop_index('idx_calendar_events_end_time', table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
