"""Add summaries table

Revision ID: 11cd07b5b675
Revises: 06b1895615e3
Create Date: 2025-11-26 17:49:06.960173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11cd07b5b675'
down_revision: Union[str, Sequence[str], None] = '06b1895615e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_id'), table_name='reminders')
    op.create_index(op.f('ix_reminders_id'), 'reminders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_id'), table_name='reminders')
    op.create_index(op.f('ix_prompts_id'), 'reminders', ['id'], unique=False)
    # ### end Alembic commands ###
