"""Add missing outcome and behavior tables

Revision ID: 8ec5d21c3589
Revises: 087e53b0fbf1
Create Date: 2025-11-23 22:47:50.888588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ec5d21c3589'
down_revision: Union[str, Sequence[str], None] = '087e53b0fbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('outcome_type', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outcomes_outcome_type', 'outcomes', ['outcome_type'], unique=False)
    op.create_index('idx_outcomes_timestamp', 'outcomes', ['timestamp'], unique=False)
    op.create_index(op.f('ix_outcomes_id'), 'outcomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_id'), table_name='outcomes')
    op.drop_index('idx_outcomes_timestamp', table_name='outcomes')
    op.drop_index('idx_outcomes_outcome_type', table_name='outcomes')
    op.drop_table('outcomes')
    # ### end Alembic commands ###
