"""Update garmin_data model with new schema

Revision ID: cad2f99ab1ba
Revises: 074081318e3a
Create Date: 2025-11-23 23:17:06.380203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cad2f99ab1ba'
down_revision: Union[str, Sequence[str], None] = '074081318e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garmin_data', sa.Column('metric_type', sa.String(length=50), nullable=False))
    op.add_column('garmin_data', sa.Column('metric_date', sa.Date(), nullable=False))
    op.add_column('garmin_data', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('garmin_data', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('garmin_data', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('garmin_data', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_garmin_data_data_type'), table_name='garmin_data')
    op.drop_index(op.f('idx_garmin_data_timestamp'), table_name='garmin_data')
    op.create_index('idx_garmin_data_metric_date', 'garmin_data', ['metric_date'], unique=False)
    op.create_index('idx_garmin_data_metric_type', 'garmin_data', ['metric_type'], unique=False)
    op.create_index('idx_garmin_data_user_date', 'garmin_data', ['user_id', 'metric_date'], unique=False)
    op.create_unique_constraint('uq_garmin_user_metric_date', 'garmin_data', ['user_id', 'metric_type', 'metric_date'])
    op.drop_column('garmin_data', 'timestamp')
    op.drop_column('garmin_data', 'data_type')
    op.drop_column('garmin_data', 'synced_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garmin_data', sa.Column('synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('garmin_data', sa.Column('data_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('garmin_data', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_garmin_user_metric_date', 'garmin_data', type_='unique')
    op.drop_index('idx_garmin_data_user_date', table_name='garmin_data')
    op.drop_index('idx_garmin_data_metric_type', table_name='garmin_data')
    op.drop_index('idx_garmin_data_metric_date', table_name='garmin_data')
    op.create_index(op.f('idx_garmin_data_timestamp'), 'garmin_data', ['timestamp'], unique=False)
    op.create_index(op.f('idx_garmin_data_data_type'), 'garmin_data', ['data_type'], unique=False)
    op.drop_column('garmin_data', 'deleted_at')
    op.drop_column('garmin_data', 'updated_at')
    op.drop_column('garmin_data', 'created_at')
    op.drop_column('garmin_data', 'fetched_at')
    op.drop_column('garmin_data', 'metric_date')
    op.drop_column('garmin_data', 'metric_type')
    # ### end Alembic commands ###
